package com.xenaksys.szcore.event.music;

public enum MusicEventType {
    TEMPO_CHANGE, TIMESIG_CHANGE, TRANSPORT_POSITION, PREP_STAVE_ACTIVE_CHANGE, STAVE_ACTIVE_CHANGE, PRECOUNT_BEAT_SETUP,
    STOP, TRANSITION, MOD_WINDOW
}
