package com.xenaksys.szcore.event;


public enum EventType {
    OSC, MUSIC, ADMIN_OUT, ADMIN_IN, CLIENT, WEB_IN, WEB_AUDIENCE_IN, WEB_OUT, WEB_AUDIENCE_OUT, WEB_AUDIENCE, WEB_SCORE_IN, WEB_SCORE_OUT, SCRIPTING_ENGINE, UNKNOWN
}
