package com.xenaksys.szcore.web;

public enum WebScoreActionType {
    PING, START, STOP, SEMAPHORE_ON, SEMAPHORE_OFF, ACTIVATE, BEAT, START_MARK, INSTRUMENT_SLOTS, RESET_INSTRUMENT_SLOTS,
    RESET_STAVES, OVERLAY_LINE, OVERLAY_ELEMENT, OVERLAY_COLOUR,
}
