package com.xenaksys.szcore.score;

public enum OverlayElementType {
    POSITION_BOX, POSITION_LINE, POSITION_BRIDGE_LINE, POSITION_ORD_LINE,
    PITCH_BOX, PITCH_LINE,
    SPEED_BOX, SPEED_LINE, SPEED_MID_LINE,
    PRESSURE_BOX, PRESSURE_LINE, PRESSURE_MID_LINE,
    DYNAMICS_BOX, DYNAMICS_LINE, DYNAMICS_MID_LINE,
}
